# Generated by Django 4.2.7 on 2025-12-27 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("IN_PROGRESS", "In Progress"),
                            ("REPAIRED", "Repaired"),
                            ("SCRAP", "Scrap"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="equipment.equipment",
                    ),
                ),
            ],
        ),
    ]
